services:
  - type: web
    name: skillsync-backend
    runtime: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -Dserver.port=$PORT -jar target/backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_VERSION
        value: 17
    healthCheckPath: /actuator/health
    plan: starter
